server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.boot.actuate.autoconfigure.tracing.zipkin: DEBUG
